### ISSUE TITLE
Encryption of (secret) binary files returns UnicodeDecodeError

### ISSUE THREAD

**Issue by Wesley-Vos** [kisst-org/kreate-kube#1]
**Problem**
I'm trying to add a binary secret file to a config map in my deployment. Therefore I'm using the following configuration:

_{{app}}-strukt.konf_
```  
strukt:
  Deployment:
    main:
      {{app}}-secret-files:
        secret_file.ext: <path in container>
  Secret:
    secret-files:
       files:
         - secret_file.ext
```

_kreate-{{app}}-{{env}}.konf_
```
file:
  secret_file.ext: dekrypt:files/secret_file.ext.encrypted
```
with the .encrypted file generated by `kreate enk file files/secret_file.ext`

Running `kreate` with this configuration returns the following error
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte`.

The secret_file.ext in this example is a JKS Keystore which is a binary file. It does work if you encrypt a non-binary file so the issue seems to be with the file format.

Let me know if more information is needed!
